### ISSUE TITLE
No wheel available on PyPI for version 0.2.2

### ISSUE THREAD

**Issue by Steap** [wireservice/agate-dbf#6]
The wheel is missing for 0.2.2. Woud it be possible to have one?

I used to always forget and ended up writing a script that runs "python3 setup.py sdist bdist_wheel && twine upload dist/*" so I don't have to remember the details for every release of my projects :)

**Comment by jpmckinney** [comment]
Thanks for the heads up! Added now.

We hadn't been releasing wheels until recently, and agate-dbf hasn't needed a new version in a while.
